language: csharp
mono: none
solution: Training.sln
dotnet: 2.0.0
script:
 - dotnet restore
 - dotnet build
 - dotnet test Training.Tests/Training.Tests.csproj
notifications:
  email:
   recipients:
    - bundit@mycostech.com
    - teerapong@mycostech.com
   on_sucess: always
   on_failure: always
